server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /var/www/ticketrush;
    index index.html;
    http2 on;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
